### PR TITLE
Matt/audio refactor

### PR DESCRIPTION
**Pull request by Fattimo**

### CODE REVIEW

**Review by cmurray191 — CHANGES_REQUESTED** [review]
Not all words' defn audio is being played. There are two circumstances where this occurs:

1. The word is capitalized in the text (e.g. Sunday on the first page) but the audio file begins with a lowercase letter (e.g. sunday.mp3). I will change all of the audio files to begin with lowercase letters (as there are a few that start with a capital letter) and if you just make the word lowercase in the url then this will fix the issue. 
2. The word shares a definition with a related word (e.g. consider and considered have the same definition) but the audio file is only named for one of the words (e.g. consider.mp3). On page 31/32, the word considered doesn't play the definition audio because of this issue. I'm not exactly sure how these words that share definitions are handled but if there is a way to check if a word shares its definition and then attempt to retrieve the audio for each of the words that share the definition until one of them works and then play that audio it should fix this issue.

**Review by cmurray191 — CHANGES_REQUESTED** [review]
Can you make the audio stop playing when the user clicks away from the definition popup (either by closing it, opening a quiz, or leaving the reading screen)

EDIT: I also noticed that the audio for a word isn't being cued when the word is clicked (i.e. the first click, when it becomes highlighted but the definition hasn't been cued yet)

**Comment by Fattimo** [comment]
> Can you make the audio stop playing when the user clicks away from the definition popup (either by closing it, opening a quiz, or leaving the reading screen)
> 
> EDIT: I also noticed that the audio for a word isn't being cued when the word is clicked (i.e. the first click, when it becomes highlighted but the definition hasn't been cued yet)

suggest just merging this in and making a ticket for overlapping audio + events. the interaction with audiobook + cueing definition audio has not been clarified, so at this present juncture there 100% will be overlapping audio with the audiobook + whatever is being cued on the word + definition side

**Comment by cmurray191** [comment]
> > Can you make the audio stop playing when the user clicks away from the definition popup (either by closing it, opening a quiz, or leaving the reading screen)
> > EDIT: I also noticed that the audio for a word isn't being cued when the word is clicked (i.e. the first click, when it becomes highlighted but the definition hasn't been cued yet)
> 
> suggest just merging this in and making a ticket for overlapping audio + events. the interaction with audiobook + cueing definition audio has not been clarified, so at this present juncture there 100% will be overlapping audio with the audiobook + whatever is being cued on the word + definition side

Gotcha. Any chance you can look at #163. It's a very small and simple change and I think it makes sense to include it in this pr.

**Review by cmurray191 — APPROVED** [review]

**Pull request merged**
