### PR TITLE
Page generation with paragraphs/lines

### PR DESCRIPTION
**Pull request by joe-lazzarini**
Add paragraphs, indents, and lines of constant sizes
Change page size to 1600

Known bugs:
Weird heading on chapter 41

### CODE REVIEW

**Comment by Fattimo** [comment]
https://www.dropbox.com/home/1339%20Awakening?preview=TEXT+-+The+Awakening+-+Kate+Chopin.docx Is it possible to make each page line up with the pages of the actual book? I think that's what the requirement has now become, but @cmurray191 to confirm.

**Comment by Fattimo** [comment]
See #80.

I used page 12 for testing purposes. The key findings are 1 line can have 72 'a' characters on it. In order to remove the indent from a text, prefix a paragraph with `&ni;` (add a space between this word and the next), and in order to break a paragraph between pages (ensure that the last line of a page is justified), suffix a paragraph with `&jl;` (also precede this word with a space)

Splitting a page between paragraphs shouldn't matter, but this should be good enough in terms of making the spacing look similar to the book in the dropbox as well as providing a solution for splitting across paragraphs.

**Review by Fattimo — CHANGES_REQUESTED** [review]
check page 140 (has overflow of 1 word) and 144 (chapter 18 seems to be cut off).

@cmurray191 if #80 is approved then merge #80 into this branch when making changes

**Comment by Fattimo** [comment]
Also, the page lengths feel inconsistent on normal desktop mode, but unsure if that is a consideration we care about @cmurray191

**Review by cmurray191 — CHANGES_REQUESTED** [review]
The words at the end of the pages have a lot of whitespace inserted between them. It seems like that is supposed to make the lines extend all the way to the margin, but it doesn't look good.

**Comment by joe-lazzarini** [comment]
Pages have been increase to 1600 characters. All above bugs should be gone, except for the stretched last lines which occur infrequently and to a more acceptable degree in my opinion. Unless I'm missing bugs I think this is about as good as it will get.

**Comment by Fattimo** [comment]
see #111 for scroll bug

**Comment by Fattimo** [comment]
image

lgtm, can be merged in for sure on m end🔥 

one concern i have is single line mid paragraph splits happen relatively often (i.e. a paragraph is split down the middle with one line left at the bottom of one page and the rest on the next or vice versa). Worst case scenario is what happens in the image, which reduces coherency.

Potentially consider adjusting script to account for "orphan" page splits

**Comment by joe-lazzarini** [comment]
Fixed, paragraphs at the end of the page are now included in full if they do not exceed the page size by more than 10%.

**Review by cmurray191 — APPROVED** [review]

**Comment by cmurray191** [comment]
Can the margins for the text window be increased slightly? Right now the text goes all of the way to the scroll bar and it makes it a little bit difficult to look at because the last character is touching the edge of the scroll bar.

**Comment by joe-lazzarini** [comment]
This would be on Matt's side

**Comment by Fattimo** [comment]
The red outline was for the sake of testing, would you like it removed or changed to a different color?

**Comment by cmurray191** [comment]
> The red outline was for the sake of testing, would you like it removed or changed to a different color?

Let's leave it as is for now. Last time I talked to Dr. Evans about the reading screen I mentioned that the outline was temporary but he said that he didn't have a problem with it being there This is something we should get his input on.

**Comment by Fattimo** [comment]
probably good to merge this pr then @cmurray191, and move future changes to the reader to new issues & new prs

**Pull request merged**
