### PR TITLE
Matt/auth

### PR DESCRIPTION
**Pull request by Fattimo**
should i add in a feature to tie localstorage data in with the auth system?

i.e. bookmarks and progress are associated with a given user

### CODE REVIEW

**Comment by Fattimo** [comment]
test@test.com
test123

OR 

test2@test.co,
test123

for a user with a name

or you can just sign up with a new user

**Comment by cmurray191** [comment]
> should i add in a feature to tie localstorage data in with the auth system?
> 
> i.e. bookmarks and progress are associated with a given user

Yes I think that is a good idea

**Comment by Fattimo** [comment]
known bug: progress wheels may persist visually when logging in from local storage

**Review by cmurray191 — CHANGES_REQUESTED** [review]
When the user enters incorrect login credentials, can the login page be refreshed with a message saying that the login credentials were incorrect rather than the current black error page?

**Review by cmurray191 — APPROVED** [review]
Looks great

**Pull request merged**
