### PR TITLE
dap

### PR DESCRIPTION
**Pull request by Fattimo**

### CODE REVIEW

**Comment by Fattimo** [comment]
can be reviewed by looking at mongodb compass of the database

**Comment by Fattimo** [comment]
additionally counts how many times a word has been cued by a user

**Review by cmurray191 — CHANGES_REQUESTED** [review]
Great work. There are a few things that I'd like to point out:

- The reader should be able to take a quiz on a word directly from the review screen (using the 'review' button on figma)
- Words that share definitions get a little messed up. Example: 'repeating' on the first page shares a definition with 'repeat'. When the quiz for repeating is cued, the word repeat is the word that actually shows up on the quiz. The review screen then shows both the word repeating and the word repeat, with the quiz results saved under the word 'repeat'. Would it be possible to have the quiz always use the word that the reader clicked on, even though it shares a definition with another word?
- If not implementing a search feature, could the cued words list at least be sorted alphabetically?
- The highest number of stars that the user has earned for a word (as can be seen on the review screen) should appear as silver stars in the quiz when the reader tries to quiz that word again. e.g. if I get three stars on a quiz and then back out of it and then go back in, I should have three silver stars instead of no silver stars

**Comment by cmurray191** [comment]
@Fattimo Sorry if I wasn't clear enough but the silver stars should appear on the quiz for a word both when it is initiated from the review screen and from the reading screen. Right now it works when the reader accesses the quiz via the review button but not on the quiz screen.

**Comment by Fattimo** [comment]
was a bug. missed a '/'

**Review by cmurray191 — APPROVED** [review]

**Pull request merged**
