### PR TITLE
Joe/definitions

### PR DESCRIPTION
**Pull request by joe-lazzarini**
## PR Title/Tagline
Python script to parse definitions and add to DB (only part 1 for now)
Run with python definitions.py -prod
This has already been run, adding to repo for the sake of the script being here

### How to Test

1. Please add or build upon a testing card to the [Notion page](http://notion.so) and link it here

### Important Changes

- Database change / migration to run
- Environment config change
- Breaking API change

### Related Github Issues

- #[Number of Issue]
- Or, remember to link to an issue on the sidebar

### Related PRs

- #PRNUMBER

### Checklist

- [ ]  Database schema docs have been updated or are not necessary
- [ ]  Code follows design and style guidelines
- [ ]  Code is commented with doc blocks
- [ ]  Tests have been written and executed or are not necessary
- [ ]  Latest code has been rebased from base branch (usually `develop`)
- [ ]  Commits follow guidelines (concise, squashed, etc)
- [ ]  Github issues have been linked in relevant commits
- [ ]  Relevant reviewers (Senior Dev/EM/Designers) have been assigned to this PR

### CODE REVIEW

**Comment by Fattimo** [comment]
see #108 for effects of this code.
image
definition contains '='

**Comment by joe-lazzarini** [comment]
Thought that was the requirement, now changed.

**Review by cmurray191 — CHANGES_REQUESTED** [review]
The definitions are not showing up now

**Comment by joe-lazzarini** [comment]
This pr does not include the changes to display the definitions, only the script to generate them. You can see the definitions in #108 as the database has been updated.

**Review by cmurray191 — APPROVED** [review]

**Pull request merged**
