### PR TITLE
definitions from db and quizzes

### PR DESCRIPTION
**Pull request by Fattimo**
to test:

go to the reader and click on `the`

### CODE REVIEW

**Review by cmurray191 — CHANGES_REQUESTED** [review]
It appears there was some miscommunication with the quiz feature. The quiz should consist of 5 questions that are all the same. The answer choices should be shuffled around after each question, but the correct answer should always be the cued word and the "question" should just be the definition of that word.

**Comment by Fattimo** [comment]
A bug exists with the bookmarks feature:
1. bookmark/unbookmark a page
2. flip page
3. the old bookmarks will be maintained.

The reason for this is because all persistent data is captured within a single local storage variable. This will be solved by moving towards a less monolithic auth system next sprint.

**Review by cmurray191 — APPROVED** [review]

**Review by cmurray191 — CHANGES_REQUESTED** [review]
Nice. Only thing left for this that I just realized is that the quiz should be on the definition of the cued word. Currently, the "definition" for the word "the" is "I sure do love testing" so when you click on the quiz button, the question should be "I sure do love testing." Right now the question seems to switch around to one of a few different questions each time you click on the quiz button.

**Review by cmurray191 — CHANGES_REQUESTED** [review]
It appears that punctuation messes with the definitions. For example, if you click on "Sunday" it brings up the word Sunday and the definition, but if you click on "Sunday;" it brings up the word "Sunday" but says that the word definition was not found. 
Furthermore, when a hyphenated word is cued, the popup displays it unhyphenated (try this with mocking-bird); the hyphen should be there in the popup and the definitions file has the hyphens in there so this might cause issues with retrieving the definition.

**Review by cmurray191 — APPROVED** [review]

**Pull request merged**
