### PR TITLE
touch

### PR DESCRIPTION
**Pull request by Fattimo**

### CODE REVIEW

**Review by cmurray191 — CHANGES_REQUESTED** [review]
Noticed a bug:

When the reader taps on a certain part of a page and then flips to the next page, the audio for the next page starts playing at around the same portion of the next page as was selected on the previous page (if that makes sense). Flipping to the next page should always start the audio from the beginning of the next page.

**Review by cmurray191 — CHANGES_REQUESTED** [review]
One more bug: Pages with a chapter heading have issues with touch playing the audio much earlier than the selected line (most likely because the heading takes up a significant amount of space on the page but is only a few characters long)

**Comment by Fattimo** [comment]
The result of this isn't because the line is later, it is because the start timestamp for the audio is "Hear a tale the awakening Chapter X blah blah blah" and then the chapter starts. Essentially, the first word of the first page doesn't start at 0:00, it starts much later, which is the cause of this bug.

The current way the feature works is that it takes the fractional position of the word on the page (i.e. if there's 500 words on a page and the user clicks word 200, the audio will scroll to `start + (200/500 - some offset) * duration`). Given this, i doubt there's an easy or consistent fix for this bug given what has been provided to us

**Comment by cmurray191** [comment]
> The result of this isn't because the line is later, it is because the start timestamp for the audio is "Hear a tale the awakening Chapter X blah blah blah" and then the chapter starts. Essentially, the first word of the first page doesn't start at 0:00, it starts much later, which is the cause of this bug.
> 
> The current way the feature works is that it takes the fractional position of the word on the page (i.e. if there's 500 words on a page and the user clicks word 200, the audio will scroll to `start + (200/500 - some offset) * duration`). Given this, i doubt there's an easy or consistent fix for this bug given what has been provided to us

Gotcha. The first chapter has a longer intro than the others (the actual page starts at 0:08) but the other chapters just have a short intro that doesn't cause as much of a lag. Any chance you can just hard code this into the first page to of the first chapter?

**Comment by Fattimo** [comment]
Something to think about but is probably fine:

With the hard coding, the first page cuts off the intro when paging to it. The intro can be replayed by disabling and then reenabling playing.

**Review by cmurray191 — APPROVED** [review]
Looks good

**Pull request merged**
