### PR TITLE
french frotnend

### PR DESCRIPTION
**Pull request by Fattimo**
there is inconsistency with how word audio is fetched. ennui, a french word on page 88, is fetched using the same word audio setup as all of the other words, however, the acceptance criteria specifies that a different audio url is used.

also, it would be preferred to use the same audio scheme for all words if that is possible

### CODE REVIEW

**Comment by Fattimo** [comment]
actually, the audio links within the issue are unclear. do they specify the definition or the word audio?

**Comment by Fattimo** [comment]
check page 32 for bon garcon

**Comment by Fattimo** [comment]
unsure of how it works with phrase audio. this is the url slug it is currently getting from a more complicated phrase:

`https://brainy-literacy-assets.s3.amazonaws.com/audio/french/allez_vous-en_allez_vous-en_sapristi.mp3 `

**Comment by cmurray191** [comment]
> unsure of how it works with phrase audio. this is the url slug it is currently getting from a more complicated phrase:
> 
> `https://brainy-literacy-assets.s3.amazonaws.com/audio/french/allez_vous-en_allez_vous-en_sapristi.mp3 `

It appears that not all of the audio is on AWS yet. I'll update you tomorrow on this.

**Comment by cmurray191** [comment]
@Fattimo @joe-lazzarini So the audio files aren't exactly consistent with the list of phrases. For the example of 'allez_vous-en_allez_vous-en_sapristi' it should be split up into 'allez_vous-en' and 'sapristi' rather than keeping it as one phrase. Other phrases need to be shortened/altered a little bit to access the audio files. If it would be helpful I can make a list of the phrases and their corresponding urls and hand that off to @joe-lazzarini

**Comment by joe-lazzarini** [comment]
Assuming @fattimo is dealing with removing punctuation, if you send me which a list of urls or phrases that match to audio I can deal with this @cmurray191

**Comment by joe-lazzarini** [comment]
@cmurray191 Do these urls include all of the french words, or phrases only?

**Comment by cmurray191** [comment]
> @cmurray191 Do these urls include all of the french words, or phrases only?

Should be everything. At least it's all of the french translation audio we have, idk if there are any french words that they just didn't record audio for.

**Comment by joe-lazzarini** [comment]
The only phrase affected by the issue @cmurray191 mentioned is allez-vous. However, the bigger problem is that the urls are not consistent - some do not include the entire phrase, and most/all remove special characters and change french to english ones 
(é -> e)
audio

I'm thinking a solution is that I parse the urls along with the words and add a field in each document for french words along the lines of 
`'audio': 'https://brainy-literacy-assets.s3.amazonaws.com/audio/french/allez_vous-en_allez_vous-en_sapristi.mp3' `
I'm not sure how slow this might be, but I don't know how else we would get these urls.
@Fattimo Let me know if this sounds good or if there is another way you want to do this

**Comment by joe-lazzarini** [comment]
Based on what Chris said, then there are also a lot of words/phrases that have no audio

**Comment by Fattimo** [comment]
> The only phrase affected by the issue @cmurray191 mentioned is allez-vous. However, the bigger problem is that the urls are not consistent - some do not include the entire phrase, and most/all remove special characters and change french to english ones (é -> e) audio
> 
> I'm thinking a solution is that I parse the urls along with the words and add a field in each document for french words along the lines of `'audio': 'https://brainy-literacy-assets.s3.amazonaws.com/audio/french/allez_vous-en_allez_vous-en_sapristi.mp3' ` I'm not sure how slow this might be, but I don't know how else we would get these urls. @Fattimo Let me know if this sounds good or if there is another way you want to do this

i think including a field with the audio link is a good solution

for special characters, I created a function that latinizes all of the special characters to their english equivalent, so as long as that is logical and works out that will solve that problem

**Comment by Fattimo** [comment]
see https://github.com/Fattimo/hear-a-tale-awakening_JIB1339/blob/235bd679d20a5ab368b378dfa8a0422c03136a6b/utils/util.js @joe-lazzarini

**Comment by joe-lazzarini** [comment]
Pr for these changes is up #187. It seems almost all french words supposedly don't have audio, so here is what I would recommend. If there is a french and an audio field for a word/phrase, use the audio field. For french words without an audio field, do whatever you are doing now which may or may not work. I am skeptical there is no audio for any of these.

**Comment by Fattimo** [comment]
> Pr for these changes is up #187. It seems almost all french words supposedly don't have audio, so here is what I would recommend. If there is a french and an audio field for a word/phrase, use the audio field. For french words without an audio field, do whatever you are doing now which may or may not work. I am skeptical there is no audio for any of these. @Fattimo

sounds good, currently, if a word cue fails, it falls back on a french url slug attempt, and i can make it fall back a third time onto a database query attempt. the only concern with this is increasing database load.

for these special cases, is it ok if I check if there is a ' ' space character within the word before querying the database? i would assume that single word french characters are handled as expected with no problems which is why i am suggesting this

**Comment by joe-lazzarini** [comment]
I'll leave that up to you. I think anything that doesn't work with these three attempts is probably very uncommon if it exists at all.

**Comment by Fattimo** [comment]
page 141 on a si tu demonstrates new functionality as detailed above @cmurray191

**Comment by Fattimo** [comment]
@joe-lazzarini either remove all periods or no periods, for page 18 mais ce phrase removed the period in the db which caused some issues

very edge case but for now don't remove any periods, my regex doesn't search for them anymore

**Comment by Fattimo** [comment]
> @joe-lazzarini either remove all periods or no periods, for page 18 mais ce phrase removed the period in the db which caused some issues
> 
> very edge case but for now don't remove any periods, my regex doesn't search for them anymore

I manually added it back in

**Comment by Fattimo** [comment]
also, half of these french words are in the part of the book that dr evans had us cut out because its the short stories after @cmurray191

**Comment by joe-lazzarini** [comment]
This period thing is probably because some of the phrases we were given have periods and most don't. It would be trivial to remove them all. Let me know if you want this.

**Comment by Fattimo** [comment]
> This period thing is probably because some of the phrases we were given have periods and most don't. It would be trivial to remove them all. Let me know if you want this.

oh i see the issue then, the given phrase didn't have a period but the reader logic attaches the period to the end of the sentence because the regex no longer parses for periods. no need to do anything, but weird edge cases like this might be good to note down in hand off documentation

**Review by cmurray191 — APPROVED** [review]
Looks good

**Pull request merged**
