### PR TITLE
Delivery Documentation

### PR DESCRIPTION
**Pull request by Fattimo**

### CODE REVIEW

**Comment by Fattimo** [comment]
@joe-lazzarini will need you to add in what scripts to run and how to configure the mongo connection string for python in delivery documentation to set up on their own database environment

**Comment by Fattimo** [comment]
> @joe-lazzarini will need you to add in what scripts to run and how to configure the mongo connection string for python in delivery documentation to set up on their own database environment

feel free to start yourself or wait for me to write up my parts and ill leave a section for you to put that

**Comment by Fattimo** [comment]
@joe-lazzarini I've included space for you. search for @joe within the readme and fill out all of those sections if possible.

**Comment by Fattimo** [comment]
@cmurray191 would it be possible for you to fill out the 1.0.0 release notes? I don't have a good grasp of all of the features we delivered without devolving the list into just stuff I did

**Review by cmurray191 — APPROVED** [review]
Let's gooo

**Pull request merged**
